/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.vars;

import com.itextpdf.text.BaseColor;
import java.awt.Color;
import java.sql.Date;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Font;
import java.io.FileOutputStream;
import java.util.Random;
import javax.swing.JOptionPane;

public class Vender extends javax.swing.JPanel {

    JPanel panel_general;
    TiendaDAO td = new TiendaDAO();
    DefaultTableModel tablamodelo;
    DefaultTableModel tablamodelo_venta;
    JTableHeader header;
    ArrayList<Object>venta = new ArrayList<Object>();
    boolean recomendFocus;
    
    
    public Vender(JPanel panel_general) {
        initComponents();
        this.panel_general = panel_general;
        JTableHeader header = tabla_venta.getTableHeader();
        this.header = header;
        recomend.setVisible(false);
        header.setFocusable(false);
        this.recomendFocus = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btcancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btvender = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_venta = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btagregar = new javax.swing.JButton();
        txtbuscar = new javax.swing.JTextField();
        txtcliente = new javax.swing.JTextField();
        txtnit = new javax.swing.JTextField();
        recomend = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablita = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        btcancelar.setBackground(new java.awt.Color(9, 67, 105));
        btcancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btcancelar.setForeground(new java.awt.Color(255, 255, 255));
        btcancelar.setText("Cancelar");
        btcancelar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcancelarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(13, 177, 215));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Vender");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btvender.setBackground(new java.awt.Color(9, 67, 105));
        btvender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btvender.setForeground(new java.awt.Color(255, 255, 255));
        btvender.setText("Vender");
        btvender.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btvender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btvenderActionPerformed(evt);
            }
        });

        tabla_venta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Precio", "Cantidad", " "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_venta.setRowHeight(30);
        tabla_venta.setSelectionBackground(new java.awt.Color(14, 176, 215));
        tabla_venta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tabla_ventaFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_venta);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Buscar:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("NIT:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Cliente:");

        btagregar.setBackground(new java.awt.Color(9, 67, 105));
        btagregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btagregar.setForeground(new java.awt.Color(255, 255, 255));
        btagregar.setText("Agregar");
        btagregar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btagregarActionPerformed(evt);
            }
        });

        Color cl = new Color(13,177,215);
        txtbuscar.setBorder(BorderFactory.createMatteBorder(0,0,1,0, cl));
        txtbuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtbuscarFocusLost(evt);
            }
        });
        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbuscarKeyTyped(evt);
            }
        });

        txtcliente.setBorder(BorderFactory.createMatteBorder(0,0,1,0, cl));

        txtnit.setBorder(BorderFactory.createMatteBorder(0,0,1,0, cl));

        tablita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablita.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tablitaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tablitaFocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(tablita);

        javax.swing.GroupLayout recomendLayout = new javax.swing.GroupLayout(recomend);
        recomend.setLayout(recomendLayout);
        recomendLayout.setHorizontalGroup(
            recomendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        recomendLayout.setVerticalGroup(
            recomendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Total:");

        txtTotal.setBorder(BorderFactory.createMatteBorder(0,0,1,0, cl));
        txtTotal.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnit, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btvender, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(recomend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btagregar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(recomend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(txtcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnit, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btvender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcancelarActionPerformed
        txtcliente.setText("");
        txtnit.setText("");
        venta = new ArrayList<Object>();
        tablamodelo_venta.setRowCount(0);
    }//GEN-LAST:event_btcancelarActionPerformed

    private void btvenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btvenderActionPerformed
        String cliente = txtcliente.getText();
        String nit = txtnit.getText();
        if(cliente.equals("") || nit.equals("")){
            JOptionPane.showMessageDialog(null,"Faltan datos del cliente","Error",JOptionPane.INFORMATION_MESSAGE);
        } else {
        for(Object row: venta){
            Object[] actual = (Object[])row;
            Object codigo = actual[0];
            Object cantidad = actual[3];
            td.reducir_stock(codigo.toString(), (Integer)cantidad);
        }
        generar_pdf(cliente,nit);
        txtcliente.setText("");
        txtnit.setText("");
        venta = new ArrayList<Object>();
        tablamodelo_venta.setRowCount(0);
        }
    }//GEN-LAST:event_btvenderActionPerformed

    private void btagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btagregarActionPerformed
        recomend.setVisible(false);
        header.setVisible(true);
        String codigo = tablita.getValueAt(tablita.getSelectedRow(), 0).toString();
        if (tablamodelo_venta != null){
        tablamodelo_venta.setRowCount(0);
    }
        Tabla_vender(codigo);
        actualizarTotal();
    }//GEN-LAST:event_btagregarActionPerformed

    private void txtbuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyTyped
        //aqui era
        
    }//GEN-LAST:event_txtbuscarKeyTyped

    private void txtbuscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtbuscarFocusLost
        //if(this.recomendFocus){
            //recomend.setVisible(false);
          //  header.setVisible(true);
        //}
    }//GEN-LAST:event_txtbuscarFocusLost

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarActionPerformed

    private void txtbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyPressed

    }//GEN-LAST:event_txtbuscarKeyPressed

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased
        header.setVisible(false);
        if (tablamodelo != null){
        tablamodelo.setRowCount(0);
    }
        Tabla_bsc();
        recomend.setVisible(true);
    }//GEN-LAST:event_txtbuscarKeyReleased

    private void tablitaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tablitaFocusGained
        this.recomendFocus = true;
    }//GEN-LAST:event_tablitaFocusGained

    private void tablitaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tablitaFocusLost
        this.recomendFocus = false;
    }//GEN-LAST:event_tablitaFocusLost

    private void tabla_ventaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tabla_ventaFocusGained
        recomend.setVisible(false);
        header.setVisible(true);
    }//GEN-LAST:event_tabla_ventaFocusGained
    
    public void Tabla_bsc(){
     String sql = "SELECT * FROM `productos` WHERE `codigo` LIKE '"+txtbuscar.getText()+"%';";
     ArrayList<producto>datos=td.listar_busqueda(sql);
     if(datos.isEmpty()){
         sql = "SELECT * FROM `productos` WHERE `nombre` LIKE '"+txtbuscar.getText()+"%';";
         datos = td.listar_busqueda(sql);
     }
     String titulos []={"Codigo","Nombre"};
     tablamodelo = new DefaultTableModel(null,titulos);
     
     for(producto general: datos){
     Object informacion []= new Object[3];
     informacion[0]=general.getCodigo();
     informacion[1]=general.getNombre();
     tablamodelo.addRow(informacion);
     }
     tablita.setModel(tablamodelo);
    }
    
    public void Tabla_vender(String codigo){
     String sql = "SELECT * FROM `productos` WHERE `codigo` LIKE '"+codigo+"%';";
     ArrayList<producto>datos=td.listar_busqueda(sql);
     String titulos []={"Codigo","Nombre","Precio","Cantidad"," "};
     tablamodelo_venta = new DefaultTableModel(null,titulos);
     
     for(producto general: datos){
     Object informacion []= new Object[4];
     informacion[0]=general.getCodigo();
     informacion[1]=general.getNombre();
     informacion[2]=general.getPrecio();
     informacion[3]=1;
     
     venta.add(informacion);
     }
     
     for(Object info: venta){
     tablamodelo_venta.addRow((Object[]) info);
     }
     
     
     TableActionEvent event = new TableActionEvent(){
         @Override
         public void onSuma(int row){
             Object valor = tablamodelo_venta.getValueAt(row,3);
             int numero = (Integer)valor + 1;
             tablamodelo_venta.setValueAt(numero,row,3);
             Object[] pos = (Object[]) venta.get(row);
             pos[3] = numero;
             actualizarTotal();
         }
         public void onResta(int row){
             Object valor = tablamodelo_venta.getValueAt(row,3);
             int numero = (Integer)valor - 1;
             if(numero == 0){

             } else{
             tablamodelo_venta.setValueAt(numero,row,3);
             Object[] pos = (Object[]) venta.get(row);
             pos[3] = numero;
             actualizarTotal();
             }
             
         }
         public void onDelete(int row){
             if(tabla_venta.isEditing()){
                 tabla_venta.getCellEditor().stopCellEditing();
             }
             DefaultTableModel model = (DefaultTableModel) tabla_venta.getModel();
             model.removeRow(row);
             venta.remove(row);
             actualizarTotal();
         }
     };
     
     tabla_venta.setModel(tablamodelo_venta);
     tabla_venta.getColumnModel().getColumn(4).setCellRenderer(new TableActionCellRender());
     tabla_venta.getColumnModel().getColumn(4).setCellEditor(new TableActionCellEditor(event));
    }
    
    public void actualizarTotal(){
        float total = 0;
        for(Object row: venta){
            Object[] actual = (Object[])row;
            Object precio = actual[2];
            Object cantidad = actual[3];
            total += ((Number)precio).floatValue() * (Integer)cantidad;
        }
        txtTotal.setText("Q"+total);
    }
    
    public void generar_pdf(String cliente,String nit){
        String codigo = generar_codigo();
        Document recivo = new Document();
        try{
            String ruta = System.getProperty("user.home");
            PdfWriter.getInstance(recivo, new FileOutputStream(ruta+"/"+cliente+codigo+".pdf"));
            String ruta_final = ruta+"/"+cliente+codigo+".pdf";
            System.out.println(ruta_final);
            recivo.open();
            recivo.add(new Paragraph("Recibo"));
            recivo.add(new Paragraph("\n"));
            recivo.add(new Paragraph("Nombre: "+cliente));
            recivo.add(new Paragraph("\n"));
            recivo.add(new Paragraph("Nit: "+nit));
            recivo.add(new Paragraph("\n"));
            recivo.add(new Paragraph("Total: "+txtTotal.getText()));
            recivo.add(new Paragraph("\n"));
            
            PdfPTable tabla = new PdfPTable(4);
            tabla.addCell("Codigo");
            tabla.addCell("Nombre");
            tabla.addCell("Precio");
            tabla.addCell("Cantidad");
            
            for(Object producto: venta){
                Object[] actual = (Object[]) producto;
                String cod = actual[0].toString();
                String name = actual[1].toString();
                String price = actual[2].toString();
                String cant = actual[3].toString();
                tabla.addCell(cod);
                tabla.addCell(name);
                tabla.addCell(price);
                tabla.addCell(cant);
             }
            
            recivo.add(tabla);
            recivo.close();
            float total = 0;
            for(Object row: venta){
            Object[] actual = (Object[])row;
            Object precio = actual[2];
            Object cantidad = actual[3];
            total += ((Number)precio).floatValue() * (Integer)cantidad;
        }
            String lista_pr = "";
            
            int cantidadP = 0;
            for(Object pr: venta){
                Object[] actual = (Object[]) pr;
                String cod = actual[0].toString();
                String name_pr = actual[1].toString();
                Object precio = actual[2];
                Object cantidad = actual[3];
                total += ((Number)precio).floatValue() * (Integer)cantidad;
                lista_pr += name_pr + ",";
                cantidadP += 1;
             }
            //lista_pr
            System.out.println(cantidadP);
            System.out.println(lista_pr);
            int id_venta = td.crear_venta(total, cliente, ruta_final);
            for(Object pr: venta){
                Object[] actual = (Object[]) pr;
                String cod = actual[0].toString();
                String name_pr = actual[1].toString();
                Object precio = actual[2];
                Object cantidad = actual[3];
                td.crear_detalle_venta_simple(id_venta, cod, (Integer)cantidad, ((Number)precio).floatValue());
             }
            
        }catch(Exception e){
            
        }
    }
    
    public String generar_codigo(){
        String codigo = "";
        Random rm = new Random();
        int l1 = rm.nextInt(26);
        int l2 = rm.nextInt(26);
        int l3 = rm.nextInt(26);
        char letra1 = (char)('a'+l1);
        char letra2 = (char)('a'+l2);
        char letra3 = (char)('a'+l3);
        int n1 = rm.nextInt(9);
        int n2 = rm.nextInt(9);
        codigo += Character.toString(letra1) + Character.toString(letra2) + Character.toString(letra3) + n1 + n2;
        return codigo;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btagregar;
    private javax.swing.JButton btcancelar;
    private javax.swing.JButton btvender;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel recomend;
    private javax.swing.JTable tabla_venta;
    private javax.swing.JTable tablita;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtcliente;
    private javax.swing.JTextField txtnit;
    // End of variables declaration//GEN-END:variables
}
